package com.pietrantuono.tests;

/**
 * Created by Peter on 15/02/2016.
 */
@SuppressWarnings("unused")
public interface ErrorCodes {

    int NO_ERROR = -1;

    int OUTSIDE_LIMITS = 1;

    // Sensor TEST Errors
    int SENSORTEST_INSUFFICIENT_SAMPLES = 2;
    int SENSORTEST_VOLTAGE_SETTING_FAILED = 3;
    int SENSORTEST_ACTIVITY_ERROR = 4;
    int SENSORTEST_NO_DRIVE_VOLTAGE_SET = 5;
    int SENSORTEST_NO_ZERO_VOLTAGE_SET = 6;
    int SENSORTEST_NO_LOAD_SET = 7;

    // Firmware Upload Errors
    int FIRMWAREUPLOAD_INIT_FAILED = 8;
    int FIRMWAREUPLOAD_GET_INFO_FAILED = 9;
    int FIRMWAREUPLOAD_FILESIZE_ERROR = 10;
    int FIRMWAREUPLOAD_WRITE_MEMORY_ERROR = 11;
    int FIRMWAREUPLOAD_DEVICE_INFO_ERROR = 12;
    int FIRMWAREUPLOAD_NO_ACK_ERROR = 13;
    int FIRMWAREUPLOAD_CMD_SEND_ERROR = 14;
    int FIRMWAREUPLOAD_ADDR_SEND_ERROR = 15;
    int FIRMWAREUPLOAD_ADDR_ALIGN_ERROR = 16;
    int FIRMWAREUPLOAD_READ_PROTECT_ERROR = 17;
    int FIRMWAREUPLOAD_ERASE_ERROR = 18;
    int FIRMWAREUPLOAD_OPTIONBYTES_WRITE_ERROR = 19;
    int FIRMWAREUPLOAD_CMD_GET_SEND_ERROR = 20;
    int FIRMWAREUPLOAD_CMD_GVR_SEND_ERROR = 21;
    int FIRMWAREUPLOAD_CMD_GID_SEND_ERROR = 22;
    int FIRMWAREUPLOAD_CMD_RM_SEND_ERROR = 23;
    int FIRMWAREUPLOAD_CMD_GO_SEND_ERROR = 24;
    int FIRMWAREUPLOAD_CMD_WM_SEND_ERROR = 25;
    int FIRMWAREUPLOAD_CMD_ER_SEND_ERROR = 26;
    int FIRMWAREUPLOAD_CMD_WP_SEND_ERROR = 27;
    int FIRMWAREUPLOAD_CMD_UW_SEND_ERROR = 28;
    int FIRMWAREUPLOAD_CMD_RP_SEND_ERROR = 29;
    int FIRMWAREUPLOAD_CMD_UR_SEND_ERROR = 30;
    int FIRMWAREUPLOAD_ERASE_EEPROM_ERROR = 31;
    int FIRMWAREUPLOAD_READ_MEMORY_ERROR = 32;

    int WAKE_NO_BLE_RECORDS = 40;
    int WAKE_NO_POST_EMAG_RECORDS = 41;
    int WAKE_BLE_RECORD_OUTSIDE_SCAN_WINDOW = 42;

    int ACCELEROMETER_SELF_TEST_ERROR = 50;
    int ACCELEROMETER_INT_PIN_ERROR = 51;

    int SENSOR_STEP_VOLTAGE_SET_ERROR = 71;
    int SENSOR_TEST_BT_CONNECTION_LOST = 72;
    int SENSOR_TEST_NO_ACTIVITY_SET = 73;
    int SENSOR_TEST_NO_VOLTAGE_SET = 74;
    int SENSOR_TEST_SAMPLES_REF_NULL = 75;
    int SENSOR_TEST_LOAD_NULL = 76;
    int SENSOR_TEST_SENSOR_RESULT_NULL = 77;
    int SENSOR_TEST_INSUFFICIENT_SAMPLES = 78;

    int CONNECTTEST_NO_SPECIFIED_DEVICE = 60;
    int CONNECTTEST_NO_DEFAULT_ADAPTER = 61;
    int CONNECTTEST_IO_EXCEPTION = 62;
    int CONNECTTEST_NO_DEVICE_INFO_SEEN = 63;

    int GENERIC_FAILURE = 100;

    int FIRMWAREUPLOAD_GENERIC_FAILURE =999;

}
