ALTER TABLE SingleTest ADD COLUMN ErrorCode INTEGER;
ALTER TABLE SingleS0 ADD COLUMN ErrorCode INTEGER;
ALTER TABLE SingleS1 ADD COLUMN ErrorCode INTEGER;
ALTER TABLE SingleS2 ADD COLUMN ErrorCode INTEGER;
